-- print('NeoVim initializing')
-- require("plugins")

require("lazy-loader")

-- require("themes_rc")
-- require("bufferline_rc")
-- require("settings_rc")
-- require("keymaps_rc")
-- require("lsp_rc")
-- require("cmp_rc")
-- require("autopairs_rc")
-- require("ts-autotag_rc")
-- require("null-ls_rc")
-- require("git-blamer_rc")
-- require("treesitter_rc")
-- require("comment_rc")
-- require("trouble_rc")
